name: Build & Run Naruto Bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t naruto-tg-bot:latest .

    - name: Run Docker container
      run: |
        docker run -d --name naruto-bot \
          -e API_ID=${{ secrets.API_ID }} \
          -e API_HASH=${{ secrets.API_HASH }} \
          -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
          naruto-tg-bot:latest
