name: Run Anime Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install PyTgCalls from GitHub
  run: pip install git+https://github.com/pytgcalls/pytgcalls.git


    - name: Run Bot
      run: python bot.py
