name: Anime Bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
  run: |
    pip install --upgrade pip
    pip install --no-cache-dir --force-reinstall -r requirements.txt

    - name: Run Bot
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        USER_STRING_SESSION: ${{ secrets.USER_STRING_SESSION }}
        FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
      run: python bot.py
